[package]
name = "ebus_generated"
version = "0.1.0"
edition = "2021"

[dependencies]
ebus_macro = { path = "../ebus_macro" }
events = { path = "../events" }
service-one = { path = "../service-one" }
service-two = { path = "../service-two" }
service-three = { path = "../service-three" }
